import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

//import lib bootstrap cho toàn dự án
import "bootstrap/dist/css/bootstrap.min.css"; //2mb
import "./globals.css";

//import fontAwesome NextJs toàn cục cho dự án
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

// import lib ToastContext vao su dung chung cho toàn dự án luôn
import ToastProvider from "@/context/ToastContext";

//import lib ModalContext vao su dung chung cho toàn dự án luôn
import ModalProvider from "@/context/ModalContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ToastProvider>
          <ModalProvider>{children}</ModalProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
